export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const SEARCH_RESTAURANTS = "SEARCH_RESTAURANTS";
export const SORT_RESTAURANTS = "SORT_RESTAURANTS";
export const SORT_RESTAURANTS_COUNTRY = "SORT_RESTAURANTS_COUNTRY";
export const FILTER_RESTAURANTS = "FILTER_RESTAURANTS";
export const ERROR = "ERROR";
